### PR TITLE
new TOS page

### PR DESCRIPTION
**Pull request by botany-lead**
new TOS page

can you take a look at this @botany-dummy-org-1/team_1

### CODE REVIEW

**Comment by botany-demo** [comment]
this is looking good @botany-dummy-org-1/team_1

**Comment by botany-lead** [comment]
i agree @botany-dummy-org-1/team_1

**Comment by botany-lead** [comment]
how about now @botany-dummy-org-1/team_1 ?

**Comment by botany-demo** [comment]
impressive work @botany-dummy-org-1/team_1

**Comment by botany-lead** [comment]
this seems fine now @botany-dummy-org-1/team_1

**Comment by botany-lead** [comment]
one more change please @botany-dummy-org-1/team_1

**Review by botany-demo — APPROVED** [review]
looks great @botany-dummy-org-1/team_1

**Review by botany-demo — APPROVED** [review]
looks great @botany-dummy-org-1/team_1

**Pull request merged**
